// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"

	model "github.com/rifkiadrn/cassandra-explore/internal/model"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login user
	// (POST /auth/login)
	LoginUser(c *fiber.Ctx) error
	// Get all blogs
	// (GET /blogs)
	Blogs(c *fiber.Ctx) error
	// Create a blog
	// (POST /blogs)
	CreateBlog(c *fiber.Ctx) error
	// Register a new user
	// (POST /users)
	RegisterUser(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(c *fiber.Ctx) error {

	return siw.Handler.LoginUser(c)
}

// Blogs operation middleware
func (siw *ServerInterfaceWrapper) Blogs(c *fiber.Ctx) error {

	c.Context().SetUserValue(model.BearerAuthScopes, []string{})

	c.Context().SetUserValue(model.ApiKeyAuthScopes, []string{})

	return siw.Handler.Blogs(c)
}

// CreateBlog operation middleware
func (siw *ServerInterfaceWrapper) CreateBlog(c *fiber.Ctx) error {

	c.Context().SetUserValue(model.BearerAuthScopes, []string{})

	c.Context().SetUserValue(model.ApiKeyAuthScopes, []string{})

	return siw.Handler.CreateBlog(c)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(c *fiber.Ctx) error {

	return siw.Handler.RegisterUser(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)

	router.Get(options.BaseURL+"/blogs", wrapper.Blogs)

	router.Post(options.BaseURL+"/blogs", wrapper.CreateBlog)

	router.Post(options.BaseURL+"/users", wrapper.RegisterUser)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RWXW/cNhD8KwTbR+U+4iRA9dRzmxZODDRwY6SFcQhoae/ERCKV5crOwdB/L5b6Op50",
	"tY06zZPP5JI7M8ud1Z1MbFFaA4acjO+kSzIolP95mtst/y3RloCkwa+qijKLZyn/pl0JMpaOUJutrCOZ",
	"WENgaHJPTx9p0m4sFopkLLWhVy9k1MVpQ7AF5MDKARpVwMQtdSQRvlQaIZXxFWcaoEQt4o9+tb/EJ173",
	"eez1J0iI0/yCoAiY+wV8qcDRWILjLA+AdIFTec7tVpsLcKU1DsY5yH4Gwz9ScAnqkrQ1MpZvPrwXfkts",
	"LApmBoZ0ovx2NFaX+fItPyJsZCx/mA/Vnrelnl9yzCH0Jn97wVH8l+31IfZSOXdr0de7UF/PwWwpk/Fy",
	"sYhkoU33/6sjeLsi7x19GZ48ie4Rfq/MPZgpEhew1Y4Ap3lMADnkcDLB4fvTb6k/VIVp9olvhPSjogc2",
	"6JEGP9KzoU5jW+je/1ijMn0crkcax7+IF/VtsSdOgGgsbx1JB0mFmnZ/csM14q5K/RZ2q4rLeSc1t3YG",
	"KgXsAMTyr2erd2fP3r7+eyCl/CnmdAoKAbvz1/6/3zop3nx4L6PGyflUszvckhGVsmZg2mxsZ2gq8XpC",
	"oXQuY4l681mrFM3y+c9bXpslthjAXfC2WKWolWE8oUv9UYIRq3dnwpWQ6E3rT+I200kmmtBrcIIy8FFs",
	"Zb8qUuL1OQMnTTnn6JY4RkbyBtA11y9ni9mCs9oSjCq1jOXJbDlb+FJR5gWeszfOczYp/7RtY+QhztXg",
	"nyC44EKZVCBQhUb0VjuTPhN6Ejz49ryveT/g6NSmu4PZoMoyb6nPPzlrhvF6nyMP99fhEyWswC80Y8Mz",
	"fb5YPG3ifij55KFiPkC4KknAuU2Vz7gMLxoEYeSZuVG5ToU2ZUVN1PJ4VIKQciVU7jj25fSNxC2ZCwd4",
	"AygA0WLQYDK+WkfSVUWhcNejrbr5Nr/O7dZrtgUvVFjVU7/7H9XVBIW7T2b/ZVUPbY2odpNqa0fCbkSD",
	"2zPtuf0OJFSed3tR/8RDUsPnzDd6q+PvpQe92eWTAWjEHIvH66L16QPtGsxCefGap8GPxB13iv6EgdvW",
	"KZLEVobG5hB8U3wbzYMU/7PcQ85QIV7v5N4ziHz3KIv4aRx12Q5ioXIEle4EfNWOntImOjn3ytsw3Dtw",
	"F4zcq3UdhUP8al3znT6l8/EV8hydy3pd/xMAAP//kgUyH2UNAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
